version: '2'
services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb-faucet
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    restart: always
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  faucet:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"